icons = "awesome"
theme = "solarized-dark"

[[block]]
block = "net"
device = "wlp58s0"
ssid = true
interval = 10
speed_up = false
speed_down = false

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
format = "%d.%m. %H:%M"
